# Generated by Django 4.2.7 on 2023-11-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiction_fountain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fictionfountain",
            name="chapters",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="fictionfountain",
            name="next_chapter_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fictionfountain",
            name="outlines",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="fictionfountain",
            name="reading_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fictionfountain",
            name="settings",
            field=models.TextField(default=""),
        ),
    ]
